name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tags:
    runs-on: ubuntu-latest

    steps:
       - name: Check out the repo
         uses: actions/checkout@v2

       - name: Install ctags
         run: |
           sudo apt-get update
           sudo apt-get install ctags

       - name: Create .tags
         run: make tags

  build:
    needs: tags
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build the program
        run: make

  install:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install the program
        run: make install
# vim: ts=2 sw=2 et
